<footer id="site-footer" class="site-footer">
  <nav class="nav">
    <ul class="menu">
      <li><a href="#">Item</a></li>
      <li><a href="#">Item</a></li>
      <li><a href="#">Item</a></li>
      <li><a href="#">Item</a></li>
      <li><a href="#">Item</a></li>
      <li><a href="#">Item</a></li>
    </ul>
    <p class="copy">Copy text text text</p>
  </nav>
  <div class="text">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi dolorum eaque eligendi, <br> ipsam molestiae mollitia nam, nemo nesciunt nisi nobis mollitia nam, nemo nesciunt nisi</p>
  </div>
</footer>