<header id="site-header" class="site-header">
  <div class="logo"><a href="#"><img src="theme/images/logo.png" alt=""></a></div>
  <h1>Lorem Lorem</h1>
  <h2>Sat, May 6, 2017</h2>
  <div class="block-social">
    <ul>
      <li class="fb"><a href="#"><img src="theme/images/tmp/social-fb.png" alt=""></a></li>
      <li class="tw"><a href="#"><img src="theme/images/tmp/social-tw.png" alt=""></a></li>
      <li class="mail"><a href="#"><img src="theme/images/tmp/social-mail.png" alt=""></a></li>
    </ul>
  </div>
</header>